version: '2'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: prod
    links:
      - pg
    expose:
      - "4000"
  pg:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
